import 'dart:convert';
import 'dart:io';

const _interactiveCountryIds = <String>['br', 'us', 'pt', 'es', 'nl'];

const _svgSourcePath = 'tool/assets/world-map-base.svg';
const _overlayDataPath = 'lib/generated/world_map_overlay_data.dart';

void main() {
  final sourceMap = _loadMercatorMap();
  final width = (sourceMap['w'] as num).toDouble();
  final height = (sourceMap['h'] as num).toDouble();
  final drawingInstructions = List<Map<String, dynamic>>.from(
    sourceMap['i'] as List,
  );
  final overlayCommands = <String, List<double>>{
    for (final id in _interactiveCountryIds) id: <double>[],
  };
  final availableInteractiveIds = <String>{};
  final basePath = StringBuffer();
  var baseShapeCount = 0;
  var interactiveCommandCount = 0;

  for (final shape in drawingInstructions) {
    final id = shape['u'] as String;
    final instructions = List<String>.from(shape['i'] as List);

    if (overlayCommands.containsKey(id)) {
      availableInteractiveIds.add(id);
      final packed = overlayCommands[id]!;
      for (final instruction in instructions) {
        _appendPackedCommand(packed, instruction);
        interactiveCommandCount++;
      }
      continue;
    }

    baseShapeCount++;
    for (final instruction in instructions) {
      _appendSvgCommand(basePath, instruction, width, height);
    }
  }

  final missingIds = _interactiveCountryIds.toSet()
    ..removeAll(availableInteractiveIds);
  if (missingIds.isNotEmpty) {
    throw StateError('Missing interactive map shapes: $missingIds');
  }

  final svgFile = File(_svgSourcePath)..parent.createSync(recursive: true);
  svgFile.writeAsStringSync(
    _buildSvg(width: width, height: height, pathData: basePath.toString()),
  );

  final overlayFile = File(_overlayDataPath)
    ..parent.createSync(recursive: true);
  overlayFile.writeAsStringSync(
    _buildOverlayData(
      width: width,
      height: height,
      baseShapeCount: baseShapeCount,
      interactiveCommandCount: interactiveCommandCount,
      commands: overlayCommands,
    ),
  );

  stdout.writeln(
    'Generated $baseShapeCount base shapes and '
    '$interactiveCommandCount interactive commands.',
  );
}

Map<String, dynamic> _loadMercatorMap() {
  final packageConfigFile = File('.dart_tool/package_config.json').absolute;
  final packageConfig = jsonDecode(packageConfigFile.readAsStringSync());
  final packages = List<Map<String, dynamic>>.from(
    packageConfig['packages'] as List,
  );
  final package = packages.firstWhere(
    (entry) => entry['name'] == 'countries_world_map',
  );
  final rootUri = packageConfigFile.uri.resolve(package['rootUri'] as String);
  final packageRoot = rootUri.path.endsWith('/')
      ? rootUri
      : rootUri.replace(path: '${rootUri.path}/');
  final source = File.fromUri(
    packageRoot.resolve('lib/data/maps/world_map.dart'),
  ).readAsStringSync();
  const declaration = 'static const String instructionsMercator =';
  final declarationStart = source.indexOf(declaration);
  if (declarationStart < 0) {
    throw StateError('Mercator instructions were not found.');
  }

  final dataStart = source.indexOf('"""', declarationStart) + 3;
  final dataEnd = source.indexOf('""";', dataStart);
  if (dataStart < 3 || dataEnd < 0) {
    throw StateError('Mercator instructions could not be extracted.');
  }

  return Map<String, dynamic>.from(
    jsonDecode(source.substring(dataStart, dataEnd)) as Map,
  );
}

void _appendPackedCommand(List<double> output, String instruction) {
  if (instruction == 'c') {
    output.addAll(const [2, 0, 0]);
    return;
  }

  final coordinates = instruction.substring(1).split(',');
  output.addAll([
    instruction[0] == 'm' ? 0 : 1,
    double.parse(coordinates[0]),
    double.parse(coordinates[1]),
  ]);
}

void _appendSvgCommand(
  StringBuffer output,
  String instruction,
  double width,
  double height,
) {
  if (instruction == 'c') {
    output.write('Z ');
    return;
  }

  final coordinates = instruction.substring(1).split(',');
  final x = double.parse(coordinates[0]) * width;
  final y = double.parse(coordinates[1]) * height;
  output
    ..write(instruction[0] == 'm' ? 'M' : 'L')
    ..write(_formatNumber(x, fractionDigits: 5))
    ..write(' ')
    ..write(_formatNumber(y, fractionDigits: 5))
    ..write(' ');
}

String _buildSvg({
  required double width,
  required double height,
  required String pathData,
}) {
  final formattedWidth = _formatNumber(width, fractionDigits: 2);
  final formattedHeight = _formatNumber(height, fractionDigits: 2);
  return '''<!-- Generated by tool/generate_world_map_assets.dart. -->
<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 $formattedWidth $formattedHeight">
  <path d="$pathData" fill="none" stroke="#42606B" stroke-opacity="0.55" stroke-width="0.75" stroke-linecap="round" stroke-linejoin="round"/>
</svg>
''';
}

String _buildOverlayData({
  required double width,
  required double height,
  required int baseShapeCount,
  required int interactiveCommandCount,
  required Map<String, List<double>> commands,
}) {
  final output = StringBuffer(
    '''// Generated by tool/generate_world_map_assets.dart.
// Do not edit by hand.

const double worldMapWidth = ${_formatNumber(width, fractionDigits: 2)};
const double worldMapHeight = ${_formatNumber(height, fractionDigits: 2)};
const worldMapBaseShapeCount = $baseShapeCount;
const worldMapInteractiveCommandCount = $interactiveCommandCount;

const worldMapInteractiveCountryOrder = <String>[
''',
  );
  for (final id in _interactiveCountryIds) {
    output.writeln("  '$id',");
  }
  output.writeln('];\n');
  output.writeln(
    'const worldMapInteractivePathCommands = <String, List<double>>{',
  );
  for (final entry in commands.entries) {
    output.writeln("  '${entry.key}': <double>[");
    for (var index = 0; index < entry.value.length; index += 3) {
      output
        ..write('    ')
        ..write(_formatNumber(entry.value[index], fractionDigits: 0))
        ..write(', ')
        ..write(_formatNumber(entry.value[index + 1], fractionDigits: 10))
        ..write(', ')
        ..write(_formatNumber(entry.value[index + 2], fractionDigits: 10))
        ..writeln(',');
    }
    output.writeln('  ],');
  }
  output.writeln('};');
  return output.toString();
}

String _formatNumber(double value, {required int fractionDigits}) {
  var formatted = value.toStringAsFixed(fractionDigits);
  if (formatted.contains('.')) {
    formatted = formatted.replaceFirst(RegExp(r'\.?0+$'), '');
  }
  return formatted == '-0' ? '0' : formatted;
}
